# Generated by Django 5.2.7 on 2025-12-18 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20, unique=True, verbose_name='課程代碼')),
                ('course_name', models.CharField(max_length=200, verbose_name='課程名稱')),
                ('course_name_en', models.CharField(blank=True, max_length=300, null=True, verbose_name='課程英文名稱')),
                ('course_type', models.CharField(choices=[('required', '必修'), ('elective', '選修'), ('general_required', '通識(必修)'), ('general_elective', '通識(選修)')], max_length=20, verbose_name='課程類別')),
                ('credits', models.IntegerField(verbose_name='學分數')),
                ('description', models.TextField(blank=True, verbose_name='課程描述')),
                ('description_en', models.TextField(blank=True, verbose_name='課程英文描述')),
                ('old_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='舊課程代碼')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '課程',
                'verbose_name_plural': '課程',
                'ordering': ['course_code'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='系所名稱')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='系所代碼')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '系所',
                'verbose_name_plural': '系所',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='學制名稱')),
            ],
            options={
                'verbose_name': '學制',
                'verbose_name_plural': '學制',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('student', '學生'), ('teacher', '教師'), ('admin', '管理員')], max_length=20, unique=True, verbose_name='角色名稱')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
            },
        ),
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=10, verbose_name='學年度')),
                ('semester', models.CharField(choices=[('1', '上學期'), ('2', '下學期')], max_length=1, verbose_name='學期')),
                ('grade_level', models.IntegerField(verbose_name='建議修課年級')),
                ('max_students', models.IntegerField(default=50, verbose_name='人數上限')),
                ('current_students', models.IntegerField(default=0, verbose_name='目前人數')),
                ('status', models.CharField(choices=[('open', '開放選課'), ('full', '已額滿'), ('closed', '停開')], default='open', max_length=10, verbose_name='開課狀態')),
                ('notes', models.TextField(blank=True, verbose_name='課表備註')),
                ('old_schedule_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='舊課表代碼')),
                ('old_schedule_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='舊課表名稱')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='accounts.course', verbose_name='課程')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='accounts.department', verbose_name='開課系所')),
            ],
            options={
                'verbose_name': '開課資料',
                'verbose_name_plural': '開課資料',
                'ordering': ['-academic_year', '-semester', 'course__course_code'],
            },
        ),
        migrations.CreateModel(
            name='CreditSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_credits', models.IntegerField(default=0, verbose_name='總學分')),
                ('required_credits', models.IntegerField(default=0, verbose_name='必修學分')),
                ('elective_credits', models.IntegerField(default=0, verbose_name='選修學分')),
                ('general_credits', models.IntegerField(default=0, verbose_name='通識學分')),
                ('passed_credits', models.IntegerField(default=0, verbose_name='已通過學分')),
                ('failed_credits', models.IntegerField(default=0, verbose_name='未通過學分')),
                ('gpa', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='學期平均 GPA')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_summary', to=settings.AUTH_USER_MODEL, verbose_name='學生')),
            ],
            options={
                'verbose_name': '學分統計',
                'verbose_name_plural': '學分統計',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('enrolled', '已選課'), ('passed', '已通過'), ('failed', '未通過'), ('dropped', '已退選')], default='enrolled', max_length=10, verbose_name='狀態')),
                ('grade', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D', 'D'), ('F', 'F')], max_length=3, null=True, verbose_name='等第成績')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='百分制成績')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='選課時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='accounts.courseoffering', verbose_name='開課')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='學生')),
            ],
            options={
                'verbose_name': '選課紀錄',
                'verbose_name_plural': '選課紀錄',
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏時間')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='accounts.courseoffering', verbose_name='開課')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_courses', to=settings.AUTH_USER_MODEL, verbose_name='學生')),
            ],
            options={
                'verbose_name': '收藏課程',
                'verbose_name_plural': '收藏課程',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfferingTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('main', '主開課'), ('co', '協同')], default='co', max_length=10, verbose_name='教師角色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offering_teachers', to='accounts.courseoffering', verbose_name='開課')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_offerings', to=settings.AUTH_USER_MODEL, verbose_name='教師')),
            ],
            options={
                'verbose_name': '開課教師',
                'verbose_name_plural': '開課教師',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=50, verbose_name='姓名')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='電子郵件')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='電話')),
                ('student_id', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='學號')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='科系')),
                ('grade', models.IntegerField(blank=True, null=True, verbose_name='年級')),
                ('office', models.CharField(blank=True, max_length=100, null=True, verbose_name='研究室')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='職稱')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('roles', models.ManyToManyField(to='accounts.role', verbose_name='角色')),
            ],
            options={
                'verbose_name': '個人資料',
                'verbose_name_plural': '個人資料',
            },
        ),
        migrations.CreateModel(
            name='ClassTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('1', '星期一'), ('2', '星期二'), ('3', '星期三'), ('4', '星期四'), ('5', '星期五'), ('6', '星期六'), ('7', '星期日')], max_length=1, verbose_name='星期幾')),
                ('start_period', models.IntegerField(verbose_name='開始節次')),
                ('end_period', models.IntegerField(verbose_name='結束節次')),
                ('classroom', models.CharField(max_length=50, verbose_name='上課地點')),
                ('weeks', models.TextField(blank=True, null=True, verbose_name='上課週次')),
                ('hours_per_week', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='每週時數')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_times', to='accounts.courseoffering', verbose_name='開課')),
            ],
            options={
                'verbose_name': '上課時段',
                'verbose_name_plural': '上課時段',
                'ordering': ['offering', 'weekday', 'start_period'],
                'indexes': [models.Index(fields=['offering'], name='accounts_cl_offerin_9c2641_idx'), models.Index(fields=['weekday', 'start_period', 'end_period'], name='accounts_cl_weekday_32a0a3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='courseoffering',
            index=models.Index(fields=['academic_year', 'semester'], name='accounts_co_academi_a01b05_idx'),
        ),
        migrations.AddIndex(
            model_name='courseoffering',
            index=models.Index(fields=['department'], name='accounts_co_departm_8b9ae5_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student'], name='accounts_en_student_a6b4c2_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['offering'], name='accounts_en_offerin_deb96f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'offering')},
        ),
        migrations.AlterUniqueTogether(
            name='favoritecourse',
            unique_together={('student', 'offering')},
        ),
        migrations.AlterUniqueTogether(
            name='offeringteacher',
            unique_together={('offering', 'teacher')},
        ),
    ]
