# Generated by Django 5.2.7 on 2025-12-24 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="teacher_id",
            field=models.CharField(
                blank=True, max_length=20, null=True, unique=True, verbose_name="教師編號"
            ),
        ),
    ]
