# Generated by Django 5.1.6 on 2025-11-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_options_alter_role_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('required', '必修'), ('elective', '選修'), ('general_required', '通識(必修)'), ('general_elective', '通識(選修)')], max_length=20, verbose_name='課程類別'),
        ),
    ]
