# Generated by Django 5.2.7 on 2025-12-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_profile_teacher_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="force_password_change",
            field=models.BooleanField(default=True, verbose_name="需強制修改密碼"),
        ),
    ]
