# Generated by Django 5.2.7 on 2025-12-26 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_force_password_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.TextField(blank=True, null=True, verbose_name='大頭貼 (Base64)'),
        ),
    ]
